#server:
#  port: 7979
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#spring:
#  jpa:
#    hibernate:
#
#      ddl-auto: none
#
#
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        show_sql: true
#
#  datasource:
#    url: jdbc:mysql://enventmanagement.mysql.database.azure.com:3306/eventmanagement?useSSL=TRUE
#    username: fptadmin
#    password: 123Khongrotmon
#    driver-class-name: com.mysql.cj.jdbc.Driver
#jwt:
#  private-key: CLp/edt3SGCOs7+ByILRGWPR5N168VSi8TG12KBe2/Y=
#  spring:
#    mail:
#      host: smtp.gmail.com
#      port: 587
#      username: swp391eventmanagement@gmail.com
#      password: atbb jgic gfsj cvvh
#      properties:
#        mail:
#          smtp:
#            auth: true
#            starttls:
#              enable: true
server:
  port: 7979

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/EventManagement
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  private-key: CLp/edt3SGCOs7+ByILRGWPR5N168VSi8TG12KBe2/Y=




